version: "3.12"

services:
  db:
    image: postgres:16-alpine
    container_name: fastapi_pet1-db-local
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fastapi_pet_1
    volumes:
      - db-data-local:/var/lib/postgresql/data
    networks:
      - local-net

  redis:
    image: redis:7-alpine
    container_name: fastapi_pet1-redis-local
    volumes:
      - redis-data-local:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-net

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fastapi_pet1-backend-local
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db/fastapi_pet_1
      SECRET_KEY: secret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ""
      REDIS_CACHE_PREFIX: "myapp:cache:"
    ports:
      - "4004:4000"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - ../:/var/www
    command: ["-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]
    networks:
      - local-net

networks:
  local-net:

volumes:
  db-data-local:
  redis-data-local:
