version: "3.12"

services:
  db:
    image: postgres:16-alpine
    container_name: fastapi_pet1-db-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fastapi_pet_1
    volumes:
      - db-data-local:/var/lib/postgresql/data
    networks:
      - local-net

  redis:
    image: redis:7-alpine
    container_name: fastapi_pet1-redis-local
    ports:
      - "6379:6379"
    networks:
      - local-net

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fastapi_pet1-backend-local
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db/fastapi_pet_1
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    volumes:
      - ../:/var/www
    command: ["-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]
    networks:
      - local-net

networks:
  local-net:

volumes:
  db-data-local:

